services:

  web:
    build: .
   
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - 8000:8000

    env_file:
      - ./.env 

    environment:
      - DATABASE=postgres 
      - SQL_ENGINE=django.db.backends.postgresql 
      - SQL_HOST=db 
      - SQL_PORT=5432



    depends_on: 
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      

volumes:
  postgres_data: